name: TEST
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}

      - name: Set up DocBook
        run: sudo apt update && sudo apt install -y docbook-xml docbook-xsl libxml2-utils xsltproc

      - name: Build document
        run: make -C ./source html-chunk

      - name: Deploy artifacts
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html-chunk
